### ISSUE TITLE
[Bug] Quasar platform plugin is not transpiled causing error in Edge/IE11

### ISSUE THREAD

**Issue by solaris7791** [quasarframework/quasar-cli#160] opened 2018-07-30 06:22 UTC
Hello,
with cli 0.17.4 the problem with transpiling platform.js for IE/Edge has reappeared
    Quasar CLI........ v0.17.5
    Quasar Framework.. v0.17.4

platform.js
...
     is: getPlatform(),
      ...getClientProperties()
Spread operator causes script error in IE/Edge

**Comment by scarry1992** [comment] 2018-07-30 14:45
How I see, mixins in quasar-framework don`t traspilling. I have same trouble.

**Comment by rstoenescu** [comment] 2018-07-31 15:55
Hi,

Can you write a minimal reproduction repo? I want to see your use-case. Details are important. Thanks.

**Comment by scarry1992** [comment] 2018-07-31 16:01
I tried on empty repo(genering by you cli). And I have that bug with transpilling. Just write in some component some ES6 construction(ex: spred/rest operator) and you see it in chunk in build. If You want to try see: [https://github.com/flespi-software/TrackIt](proj)

**Comment by rstoenescu** [comment] 2018-07-31 16:36
Got it. Reproduced issue. Under investigation.

**Comment by rstoenescu** [comment] 2018-07-31 17:52
Fix is being currently tested. You can do too if you replace the Quasar CLI version to this exact version: "0.17.0-beta.36".

**Comment by rstoenescu** [comment] 2018-07-31 19:54
I saw you are also importing uncompiled .vue files from node_modules. This is not good practice. But anyway, added exception for Babel to also transpile any .vue file in node_modules. Try with "0.17.0-beta.37". On your app there's still an error in IE11, but it's not related to Quasar.

**Comment by solaris7791** [comment] 2018-07-31 20:01
hi, if it helps, I fixed the issue for me, after adding a small fix in quasar.conf.js in 
chainWebpack(chain) {
  chain.module.rule('babel').exclude.clear()
}

seems the exclude of node_modules in create-chain.js is the cause.

**Comment by scarry1992** [comment] 2018-07-31 20:24
Can You tell me pls, Why in 15.*.* cli .vue files from node_modules transpiring normally, but now we have a troubles? Anything troubles with babel? And I tried 38beta, and now don't transpilling another file then before. Maybe I can help you with it? Now you chaining vue-loader - babel, but before you chained babel - [vue-loader with babel]. Maybe bug is here?

**Comment by rstoenescu** [comment] 2018-07-31 21:46
Since v0.15 the webpack version changed, the babel version changed, and there's a logical error in webpack now with the include/exclude. Fails on some particular linux versions... anyway, long explanation. Did you test with beta.39? Please contact me on Discord to speed things up.

**Comment by rstoenescu** [comment] 2018-07-31 21:55
Also, other vue-loader in v0.15... lots changed in these packages.

**Comment by rstoenescu** [comment] 2018-08-01 04:47
Fixed in CLI v0.17.6.

**Closed by rstoenescu** 2018-08-01 04:47 UTC

**Comment by mpacary** [comment] 2019-01-11 13:53
Had exact same issue with quasar-cli 0.17.23
I had to play in quasar.conf with "include" rules in `extendWebpack (cfg) { ... }` section to avoid the error.

Something like this:

        // UGLY HACK to force babel to transpile quasar-framework files
        // see https://github.com/quasarframework/quasar-cli/issues/160
        cfg.module.rules[1].include = [
          // specific paths of your app that you need to be transpiled
          path.resolve(__dirname, "src/plugins"),
          path.resolve(__dirname, "src/router"),
          path.resolve(__dirname, "src/store"),
          // quasar framework paths
          path.resolve(__dirname, ".quasar"),
          path.resolve(__dirname, "node_modules/quasar-framework") // otherwise src/plugins/platform.js is not transpiled and contains ES6 specific code 
        ]

I could not override easily the "exclude" function on the fly and already had a list of "include" directories instead, but overriding the "exclude" function could be also a workaround.
